# Generated by Django 5.0.2 on 2024-04-24 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('phone_num', models.IntegerField()),
                ('payment_method', models.CharField(choices=[('credit', 'Credit'), ('card', 'Card'), ('paypal', 'Paypal')], max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='customusers',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customusers',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='customusers',
            name='phone_num',
        ),
    ]
