# Generated by Django 5.0.2 on 2024-06-09 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapi', '0002_orderitem_price_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
