# Generated by Django 5.0.2 on 2024-04-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapi', '0003_role_refreshtoken_customusers_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
    ]
