# Generated by Django 5.0.2 on 2024-04-27 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapi', '0004_alter_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='role',
        ),
    ]
