# Generated by Django 5.0.2 on 2024-04-27 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapi', '0005_remove_customusers_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ecomapi.role'),
        ),
    ]
