# Generated by Django 5.0.2 on 2024-06-10 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapi', '0005_remove_orderitem_price'),
    ]

    operations = [
    ]
