# Generated by Django 5.0.2 on 2024-05-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapi', '0007_alter_customusers_role_alter_payment_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Debit/Credit Cards', max_length=100),
        ),
    ]
