# Generated by Django 5.0.2 on 2024-06-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapi', '0007_alter_review_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='estimated_delivery_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='shipping_address',
            field=models.TextField(max_length=2000),
        ),
    ]
