# Generated by Django 5.0.2 on 2024-06-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapi', '0008_alter_shipping_estimated_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='user_id',
        ),
        migrations.AddField(
            model_name='shipping',
            name='country',
            field=models.CharField(default='Nigeria', max_length=100),
        ),
        migrations.AddField(
            model_name='shipping',
            name='payment_method',
            field=models.CharField(default='Debit/Credit Cards', max_length=100),
        ),
        migrations.AddField(
            model_name='shipping',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
