# Generated by Django 5.0.2 on 2024-05-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapi', '0008_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='Debit/Credit Cards', max_length=100),
        ),
    ]
