# Generated by Django 5.0.2 on 2024-06-12 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapi', '0009_remove_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='order_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='Ecomapi.order'),
        ),
    ]
