# Generated by Django 5.0.2 on 2024-05-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapi', '0009_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
    ]
