# Generated by Django 5.0.2 on 2024-05-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapi', '0010_cart_quantity_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'pending'), ('complete', 'complete'), ('   failed', 'failed')], default='pending', max_length=50),
        ),
    ]
