# Generated by Django 5.0.6 on 2024-06-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapi', '0011_alter_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='role',
        ),
    ]
