# Generated by Django 5.0.2 on 2024-05-10 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapi', '0013_alter_customusers_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RefreshToken',
            new_name='RefreshTokens',
        ),
    ]
