# Generated by Django 5.0.2 on 2024-05-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapi', '0014_rename_refreshtoken_refreshtokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtokens',
            name='expires_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
