# Generated by Django 5.0.2 on 2024-05-10 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapi', '0015_alter_refreshtokens_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ecomapi.role'),
            preserve_default=False,
        ),
    ]
