# Generated by Django 5.0.2 on 2024-05-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapi', '0016_alter_customusers_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='subtotal',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
