# Generated by Django 5.0.2 on 2024-05-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapi', '0019_remove_cartitems_subtotal_alter_cartitems_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='sub_total',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
