# Generated by Django 5.0.2 on 2024-05-21 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapi', '0020_cartitems_sub_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='sub_total',
        ),
    ]
