# Generated by Django 5.0.2 on 2024-05-25 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapi', '0022_alter_cartitems_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecomapi.role'),
        ),
    ]
