# Generated by Django 5.0.2 on 2024-05-30 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapi', '0025_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
